### PR TITLE
Add referral link on Era Swap Life user dashboard

### PR DESCRIPTION
**Pull request by zemse**
When user loads their wallet on Era Swap Life, they will see a referral link option. They can copy their referral link, use whatsapp, twitter, facebook, linkedin, telegram links. The generated link takes referred user to a welcome message.

### CODE REVIEW

**Comment by zemse** [comment]
@Ashish0235 can u send the link which got this error?

**Comment by Ashish0235** [comment]
Yes, Please find the below.

Twitter - https://eraswap-life-git-fork-zemse-update2.eraswap.now.sh/invite?platform=esl
LinkedIn - eraswap-life-git-fork-zemse-update2.eraswap.now.sh
Screenshot_31
Screenshot_32

**Comment by Ashish0235** [comment]
Only Telegram, Twitter link woking.

**FB link not working**.--
image

**Linkedln link-**
image

**Comment by Ashish0235** [comment]
Now Avatar showing. Thanks @zemse

**Comment by zemse** [comment]
> FB link not working.--

@Ashish0235 I checked posting link to Facebook, initially it does appear that it's incomplete link in the fb post preview but I proceeded posting the link. Later when you'll click on the link, it will expand the link with referral address and give the correct page. Please try once and confirm.

**Pull request merged**
